{
  canopen_chain_node,
  canopen_motor_node,
  catkin,
  cob_android_script_server,
  cob_base_controller_utils,
  cob_base_velocity_smoother,
  cob_bms_driver,
  cob_calibration_data,
  cob_cam3d_throttle,
  cob_collision_monitor,
  cob_collision_velocity_filter,
  cob_command_gui,
  cob_control_mode_adapter,
  cob_dashboard,
  cob_default_env_config,
  cob_default_robot_behavior,
  cob_default_robot_config,
  cob_docker_control,
  cob_frame_tracker,
  cob_hand_bridge,
  cob_hardware_config,
  cob_helper_tools,
  cob_image_flip,
  cob_light,
  cob_linear_nav,
  cob_mecanum_controller,
  cob_mimic,
  cob_monitoring,
  cob_moveit_config,
  cob_obstacle_distance,
  cob_omni_drive_controller,
  cob_phidget_em_state,
  cob_phidget_power_state,
  cob_phidgets,
  cob_reflector_referencing,
  cob_safety_controller,
  cob_scan_unifier,
  cob_script_server,
  cob_sick_lms1xx,
  cob_sick_s300,
  cob_sound,
  cob_supported_robots,
  cob_teleop,
  cob_twist_controller,
  cob_voltage_control,
  compressed_depth_image_transport,
  compressed_image_transport,
  controller_manager,
  costmap_2d,
  diagnostic_aggregator,
  generic_throttle,
  image_proc,
  joint_state_controller,
  joint_state_publisher,
  joint_trajectory_controller,
  joy,
  laser_filters,
  nodelet,
  openni2_launch,
  position_controllers,
  realsense2_camera,
  rgbd_launch,
  robot_state_publisher,
  roslaunch,
  rosserial_python,
  rosserial_server,
  rostopic,
  rviz,
  spacenav_node,
  tf2_ros,
  theora_image_transport,
  topic_tools,
  twist_mux,
  usb_cam,
  velocity_controllers,

  buildColconPackage,
  final,
  srcs,
}:

buildColconPackage {
  name = "cob_bringup";
  pkgFinal = final.noetic.cob_bringup;
  src = srcs.cob_robots.cob_bringup;

  colconBuildDepends = [
    catkin
  ];

  colconRunDepends = [
    canopen_chain_node
    canopen_motor_node
    cob_android_script_server
    cob_base_controller_utils
    cob_base_velocity_smoother
    cob_bms_driver
    cob_calibration_data
    cob_cam3d_throttle
    cob_collision_monitor
    cob_collision_velocity_filter
    cob_command_gui
    cob_control_mode_adapter
    cob_dashboard
    cob_default_env_config
    cob_default_robot_behavior
    cob_default_robot_config
    cob_docker_control
    cob_frame_tracker
    cob_hand_bridge
    cob_hardware_config
    cob_helper_tools
    cob_image_flip
    cob_light
    cob_linear_nav
    cob_mecanum_controller
    cob_mimic
    cob_monitoring
    cob_moveit_config
    cob_obstacle_distance
    cob_omni_drive_controller
    cob_phidget_em_state
    cob_phidget_power_state
    cob_phidgets
    cob_reflector_referencing
    cob_safety_controller
    cob_scan_unifier
    cob_script_server
    cob_sick_lms1xx
    cob_sick_s300
    cob_sound
    cob_teleop
    cob_twist_controller
    cob_voltage_control
    compressed_depth_image_transport
    compressed_image_transport
    controller_manager
    costmap_2d
    diagnostic_aggregator
    generic_throttle
    image_proc
    joint_state_controller
    joint_state_publisher
    joint_trajectory_controller
    joy
    laser_filters
    nodelet
    openni2_launch
    position_controllers
    realsense2_camera
    rgbd_launch
    robot_state_publisher
    rosserial_python
    rosserial_server
    rostopic
    rviz
    spacenav_node
    tf2_ros
    theora_image_transport
    topic_tools
    twist_mux
    usb_cam
    velocity_controllers
  ];

  colconTestDepends = [
    cob_supported_robots
    roslaunch
  ];
}
