{
  angles,
  catkin,
  checkerboard_detector,
  cmake_modules,
  cv_bridge,
  dynamic_reconfigure,
  eigen,
  fetch_description,
  geometry_msgs,
  git,
  image_geometry,
  image_transport,
  image_view,
  image_view2,
  imagesift,
  jsk_data,
  jsk_gui_msgs,
  jsk_recognition_msgs,
  jsk_recognition_utils,
  jsk_rqt_plugins,
  jsk_tools,
  jsk_topic_tools,
  leveldb,
  libcmt,
  libuvc_camera,
  libyamlcpp,
  message_generation,
  message_runtime,
  mk,
  nodelet,
  opencv_apps,
  openni2_launch,
  pcl_ros,
  posedetection_msgs,
  python3Packages,
  pythonPackages,
  robot_self_filter,
  rosbag,
  roscpp,
  roseus,
  roslaunch,
  roslint,
  rospack,
  rospy,
  rostest,
  rostopic,
  rqt_gui,
  rviz,
  sensor_msgs,
  sound_play,
  std_msgs,
  tf,
  tf2_geometry_msgs,
  topic_tools,

  buildColconPackage,
  final,
  srcs,
}:

buildColconPackage {
  name = "jsk_perception";
  pkgFinal = final.noetic.jsk_perception;
  src = srcs.jsk_recognition.jsk_perception;

  colconBuildDepends = [
    angles
    catkin
    cmake_modules
    cv_bridge
    dynamic_reconfigure
    eigen
    geometry_msgs
    git
    image_geometry
    image_transport
    image_view2
    jsk_data
    jsk_recognition_msgs
    jsk_recognition_utils
    jsk_topic_tools
    libcmt
    libuvc_camera
    libyamlcpp
    message_generation
    mk
    nodelet
    opencv_apps
    pcl_ros
    posedetection_msgs
    robot_self_filter
    roscpp
    roseus
    rospack
    sensor_msgs
    std_msgs
    tf
  ];

  colconRunDepends = [
    angles
    checkerboard_detector
    cv_bridge
    dynamic_reconfigure
    eigen
    fetch_description
    geometry_msgs
    image_geometry
    image_transport
    image_view
    image_view2
    imagesift
    jsk_data
    jsk_gui_msgs
    jsk_recognition_msgs
    jsk_recognition_utils
    jsk_rqt_plugins
    jsk_topic_tools
    leveldb
    libcmt
    libuvc_camera
    libyamlcpp
    message_runtime
    mk
    nodelet
    opencv_apps
    openni2_launch
    pcl_ros
    posedetection_msgs
    python3Packages.boto3
    python3Packages.h5py
    python3Packages.pyyaml
    python3Packages.scikitlearn
    pythonPackages.chainer
    pythonPackages.dlib
    robot_self_filter
    rosbag
    roscpp
    roseus
    rospack
    rospy
    rostopic
    rqt_gui
    rviz
    sensor_msgs
    sound_play
    std_msgs
    tf
    tf2_geometry_msgs
    topic_tools
  ];

  colconTestDepends = [
    jsk_tools
    roslaunch
    roslint
    rostest
  ];
}
